version: '2'
services:
  wordpress:
    container_name: server
    image: visiblevc/wordpress:latest
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./data:/data
      - ./wordpress/wp-content/themes/qedit:/app/wp-content/themes/qedit #Theme
      - ./wordpress/wp-content/plugins/advanced-custom-fields:/app/wp-content/plugins/advanced-custom-fields #Plugin
      - ./wordpress/wp-content/plugins/custom-post-type-ui:/app/wp-content/plugins/custom-post-type-ui #Plugin
      - ./wordpress/wp-content/plugins/masterslider:/app/wp-content/plugins/masterslider #Plugin
      - ./wordpress/wp-content/plugins/page-scroll-to-id:/app/wp-content/plugins/page-scroll-to-id #Plugin
      - ./wordpress/wp-content/plugins/simple-custom-post-order:/app/wp-content/plugins/simple-custom-post-order #Plugin
      - ./wordpress/wp-content/plugins/simple-image-sizes:/app/wp-content/plugins/simple-image-sizes #Plugin
      - ./wordpress/wp-content/uploads:/app/wp-content/uploads #Uploads
    environment:
      PLUGINS: >-
        [local]advanced-custom-fields,
        [local]custom-post-type-ui,
        [local]masterslider,
        [local]page-scroll-to-id,
        [local]simple-custom-post-order,
        [local]simple-image-sizes
      THEMES: >-
        [local]qedit
      DB_NAME: qedit
      DB_PASS: root
      ADMIN_EMAIL: admin@qedit.com
  db:
    container_name: db
    image: mariadb:10 # or mysql:5.7
    volumes:
      - data_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 22222:80
volumes:
  data_volume:
